from __future__ import annotations

import importlib.util
from pathlib import Path


MODULE_PATH = Path(__file__).resolve().parents[1] / "scripts" / "audit_publication_readiness.py"
SPEC = importlib.util.spec_from_file_location("audit_publication_readiness_script", MODULE_PATH)
assert SPEC and SPEC.loader
SCRIPT = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(SCRIPT)


def test_publication_readiness_audit_writes_blocking_checks(tmp_path: Path) -> None:
    payload = SCRIPT.audit_publication_readiness(output_dir=tmp_path)

    summary = payload["summary"]
    assert summary["blocking_passed"] is True
    assert summary["readiness_level"] == "paper_draft_ready"
    assert summary["blocking_failed_count"] == 0

    checks = {row["check_id"]: row for row in payload["checks"]}
    assert checks["ledger_has_no_missing_sources"]["passed"] is True
    assert checks["ledger_includes_negative_results"]["passed"] is True
    assert checks["visual_hard_slice_design_exists"]["passed"] is True
    assert checks["visual_hard_slice_execute_packet_exists"]["passed"] is True
    assert checks["visual_hard_slice_v5_vs_v4_comparison_exists"]["passed"] is True
    assert checks["visual_hard_slice_exactness_diagnostic_exists"]["passed"] is True
    assert checks["h1l_visual_executor_equivalence_packet_exists"]["passed"] is True
    assert checks["h1m_visual_alias_repeat_packet_exists"]["passed"] is True
    assert checks["visual_hard_slice_live_replay_comparison_exists"]["passed"] is True
    assert checks["visual_hard_slice_live_contracted_comparison_exists"]["passed"] is True
    assert checks["visual_hard_slice_live_role_catalog_comparison_exists"]["passed"] is True
    assert checks["visual_hard_slice_live_argument_hints_comparison_exists"]["passed"] is True
    assert checks["visual_hard_slice_live_schema_literals_comparison_exists"]["passed"] is True
    assert checks["visual_hard_slice_stress_packet_exists"]["passed"] is True
    assert checks["visual_hard_slice_stress_schema_field_comparison_exists"]["passed"] is True
    assert checks["visual_hard_slice_stress_report_table_exists"]["passed"] is True
    assert checks["visual_live_stress_diagnostic_exists"]["passed"] is True
    assert checks["visual_hard_slice_alias_repeat_packet_exists"]["passed"] is True
    assert checks["visual_hard_slice_alias_repeat_schema_field_comparison_exists"]["passed"] is True
    assert checks["visual_hard_slice_alias_repeat_contracted_comparison_exists"]["passed"] is True
    assert checks["visual_hard_slice_alias_repeat_role_catalog_comparison_exists"]["passed"] is True
    assert checks["visual_hard_slice_alias_repeat_argument_hints_comparison_exists"]["passed"] is True
    assert checks["visual_hard_slice_alias_repeat_schema_literals_comparison_exists"]["passed"] is True
    assert checks["visual_hard_slice_alias_repeat_report_table_exists"]["passed"] is True
    assert checks["visual_alias_repeat_diagnostic_exists"]["passed"] is True
    assert checks["h1m_visual_alias_repeat_report_table_exists"]["passed"] is True
    assert checks["packaged_replay_gap_diagnostic_exists"]["passed"] is True
    assert checks["visual_hard_slice_alias_transfer_packet_exists"]["passed"] is True
    assert checks["visual_hard_slice_alias_transfer_argument_hints_comparison_exists"]["passed"] is True
    assert checks["visual_hard_slice_alias_transfer_contracted_comparison_exists"]["passed"] is True
    assert checks["visual_hard_slice_alias_transfer_report_table_exists"]["passed"] is True
    assert checks["visual_alias_transfer_diagnostic_exists"]["passed"] is True
    assert checks["h1n_alias_transfer_contract_split_diagnostic_exists"]["passed"] is True
    assert checks["h1n_alias_transfer_oracle_packet_exists"]["passed"] is True
    assert checks["h1n_alias_transfer_oracle_argument_hints_comparison_exists"]["passed"] is True
    assert checks["h1n_alias_transfer_oracle_diagnostic_exists"]["passed"] is True
    assert checks["h1n_alias_transfer_oracle_report_table_exists"]["passed"] is True
    assert checks["h1n_oracle_helper_ablation_diagnostic_exists"]["passed"] is True
    assert checks["h1n_oracle_helper_ablation_no_repair_comparison_exists"]["passed"] is True
    assert checks["h1n_alias_transfer_repeat_packet_exists"]["passed"] is True
    assert checks["h1n_alias_transfer_repeat_diagnostic_exists"]["passed"] is True
    assert checks["h1n_alias_transfer_repeat_argument_hints_comparison_exists"]["passed"] is True
    assert checks["h1n_oracle_transfer_synthesis_report_exists"]["passed"] is True
    assert checks["h1n_alias_transfer_oblique_packet_exists"]["passed"] is True
    assert checks["h1n_alias_transfer_oblique_diagnostic_exists"]["passed"] is True
    assert checks["h1n_alias_transfer_oblique_argument_hints_comparison_exists"]["passed"] is True
    assert checks["h1n_oblique_miss_analysis_exists"]["passed"] is True
    assert checks["h1n_oblique_code_hints_packet_exists"]["passed"] is True
    assert checks["h1n_oblique_code_hints_vs_argument_hints_comparison_exists"]["passed"] is True
    assert checks["h1n_oblique_code_hints_delta_diagnostic_exists"]["passed"] is True
    assert checks["h1n_code_hints_transfer_packet_exists"]["passed"] is True
    assert checks["h1n_code_hints_repeat_transfer_packet_exists"]["passed"] is True
    assert checks["h1n_code_hints_transfer_synthesis_exists"]["passed"] is True
    assert checks["h1n_oblique_code_guard_packet_exists"]["passed"] is True
    assert checks["h1n_oblique_code_guard_vs_argument_hints_comparison_exists"]["passed"] is True
    assert checks["h1n_oblique_code_guard_vs_code_hints_comparison_exists"]["passed"] is True
    assert checks["h1n_code_guard_transfer_packet_exists"]["passed"] is True
    assert checks["h1n_code_guard_repeat_transfer_packet_exists"]["passed"] is True
    assert checks["h1n_code_guard_transfer_synthesis_exists"]["passed"] is True
    assert checks["h1n_post_repair_holdout_packet_exists"]["passed"] is True
    assert checks["h1n_post_repair_code_guard_packet_exists"]["passed"] is True
    assert checks["h1n_post_repair_code_guard_vs_argument_hints_comparison_exists"]["passed"] is True
    assert checks["h1n_post_repair_diagnostic_exists"]["passed"] is True
    assert checks["h1n_post_repair_report_table_exists"]["passed"] is True
    assert checks["h1n_residual_holdout_packet_exists"]["passed"] is True
    assert checks["h1n_residual_hybrid_label_guard_packet_exists"]["passed"] is True
    assert checks["h1n_residual_hybrid_vs_code_guard_comparison_exists"]["passed"] is True
    assert checks["h1n_residual_diagnostic_exists"]["passed"] is True
    assert checks["h1n_residual_report_table_exists"]["passed"] is True
    assert checks["h1n_component_value_packet_exists"]["passed"] is True
    assert checks["h1n_component_value_v9_live_packet_exists"]["passed"] is True
    assert checks["h1n_component_value_v10_live_packet_exists"]["passed"] is True
    assert checks["h1n_component_value_v10_comparison_exists"]["passed"] is True
    assert checks["h1n_component_value_diagnostic_exists"]["passed"] is True
    assert checks["h1n_component_value_report_table_exists"]["passed"] is True
    assert checks["h1n_no_call_rescue_transfer_synthesis_exists"]["passed"] is True
    assert checks["h1o_control_factorial_packet_exists"]["passed"] is True
    assert checks["h1o_control_factorial_argument_hints_packet_exists"]["passed"] is True
    assert checks["h1o_control_factorial_component_value_packet_exists"]["passed"] is True
    assert checks["h1o_control_factorial_argument_hints_comparison_exists"]["passed"] is True
    assert checks["h1o_control_factorial_diagnostic_exists"]["passed"] is True
    assert checks["h1o_control_factorial_synthesis_exists"]["passed"] is True
    assert checks["h1p_component_value_holdout_packet_exists"]["passed"] is True
    assert checks["h1p_component_value_no_directive_live_exists"]["passed"] is True
    assert checks["h1p_component_value_component_guard_live_exists"]["passed"] is True
    assert checks["h1p_component_value_component_guard_comparison_exists"]["passed"] is True
    assert checks["h1p_component_value_diagnostic_exists"]["passed"] is True
    assert checks["h1p_component_value_report_table_exists"]["passed"] is True
    assert checks["h1q_component_label_guard_h1n_live_exists"]["passed"] is True
    assert checks["h1q_component_label_guard_h1o_live_exists"]["passed"] is True
    assert checks["h1q_component_label_guard_h1p_live_exists"]["passed"] is True
    assert checks["h1q_component_label_guard_synthesis_exists"]["passed"] is True
    assert checks["h1q_component_label_guard_report_table_exists"]["passed"] is True
    assert checks["h1s_component_residual_h1n_live_exists"]["passed"] is True
    assert checks["h1s_component_residual_h1o_live_exists"]["passed"] is True
    assert checks["h1s_component_residual_h1p_live_exists"]["passed"] is True
    assert checks["h1s_component_residual_synthesis_exists"]["passed"] is True
    assert checks["h1s_component_residual_report_table_exists"]["passed"] is True
    assert checks["h1y_routed_residual_no_directive_live_exists"]["passed"] is True
    assert checks["h1y_routed_residual_v12_live_exists"]["passed"] is True
    assert checks["h2a_visual_stale_selection_gate_live_exists"]["passed"] is True
    assert checks["h2a_visual_stale_selection_gate_vs_v11_comparison_exists"]["passed"] is True
    assert checks["h2a_visual_stale_selection_gate_vs_v12_comparison_exists"]["passed"] is True
    assert checks["h1y_routed_residual_synthesis_exists"]["passed"] is True
    assert checks["h1y_routed_residual_report_table_exists"]["passed"] is True
    assert checks["h1y_routed_residual_report_figure_exists"]["passed"] is True
    assert checks["h2a_transfer_h1n_live_exists"]["passed"] is True
    assert checks["h2a_transfer_h1o_live_exists"]["passed"] is True
    assert checks["h2a_transfer_h1p_live_exists"]["passed"] is True
    assert checks["h2a_transfer_h1x_live_exists"]["passed"] is True
    assert checks["h2a_stale_selection_transfer_synthesis_exists"]["passed"] is True
    assert checks["h2a_stale_selection_transfer_report_table_exists"]["passed"] is True
    assert checks["h2a_stale_selection_transfer_residual_table_exists"]["passed"] is True
    assert checks["h2a_stale_selection_transfer_report_figure_exists"]["passed"] is True
    assert checks["h2b_residual_exactness_packet_exists"]["passed"] is True
    assert checks["h2b_residual_exactness_no_directive_live_exists"]["passed"] is True
    assert checks["h2b_residual_exactness_v11_live_exists"]["passed"] is True
    assert checks["h2b_residual_exactness_v12_live_exists"]["passed"] is True
    assert checks["h2b_residual_exactness_v15_live_exists"]["passed"] is True
    assert checks["h2b_residual_exactness_h2a_live_exists"]["passed"] is True
    assert checks["h2b_residual_exactness_v9_live_exists"]["passed"] is True
    assert checks["h2b_residual_exactness_synthesis_exists"]["passed"] is True
    assert checks["h2b_residual_exactness_report_table_exists"]["passed"] is True
    assert checks["h2b_residual_exactness_case_table_exists"]["passed"] is True
    assert checks["h2b_residual_exactness_report_figure_exists"]["passed"] is True
    assert checks["h2c_scoped_residual_live_exists"]["passed"] is True
    assert checks["h2c_scoped_residual_vs_v12_comparison_exists"]["passed"] is True
    assert checks["h2c_scoped_residual_vs_h2a_comparison_exists"]["passed"] is True
    assert checks["h2c_scoped_residual_synthesis_exists"]["passed"] is True
    assert checks["h2c_scoped_residual_report_table_exists"]["passed"] is True
    assert checks["h2c_scoped_residual_comparison_table_exists"]["passed"] is True
    assert checks["h2c_scoped_residual_report_figure_exists"]["passed"] is True
    assert checks["h2l_target_normalization_overreach_packet_exists"]["passed"] is True
    assert checks["h2l_target_normalization_overreach_h2e_live_exists"]["passed"] is True
    assert checks["h2l_target_normalization_overreach_h2j_live_exists"]["passed"] is True
    assert checks["h2l_target_normalization_overreach_no_stale_live_exists"]["passed"] is True
    assert checks["h2l_target_normalization_overreach_h2j_vs_h2e_comparison_exists"]["passed"] is True
    assert checks["h2l_target_normalization_overreach_h2j_vs_no_stale_comparison_exists"]["passed"] is True
    assert checks["h2l_target_normalization_overreach_synthesis_exists"]["passed"] is True
    assert checks["h2l_target_normalization_overreach_report_figure_exists"]["passed"] is True
    assert checks["h2m_less_direct_overreach_packet_exists"]["passed"] is True
    assert checks["h2m_less_direct_overreach_h2e_live_exists"]["passed"] is True
    assert checks["h2m_less_direct_overreach_h2j_live_exists"]["passed"] is True
    assert checks["h2m_less_direct_overreach_no_stale_live_exists"]["passed"] is True
    assert checks["h2m_less_direct_overreach_h2j_vs_h2e_comparison_exists"]["passed"] is True
    assert checks["h2m_less_direct_overreach_h2j_vs_no_stale_comparison_exists"]["passed"] is True
    assert checks["h2m_less_direct_overreach_synthesis_exists"]["passed"] is True
    assert checks["h2m_less_direct_overreach_report_figure_exists"]["passed"] is True
    assert checks["h2n_scoped_target_normalization_h2m_live_exists"]["passed"] is True
    assert checks["h2n_scoped_target_normalization_h2k_live_exists"]["passed"] is True
    assert checks["h2n_scoped_target_normalization_h2l_live_exists"]["passed"] is True
    assert checks["h2n_scoped_target_normalization_h2f_live_exists"]["passed"] is True
    assert checks["h2n_scoped_target_normalization_vs_h2j_h2m_comparison_exists"]["passed"] is True
    assert checks["h2n_scoped_target_normalization_vs_h2e_h2m_comparison_exists"]["passed"] is True
    assert checks["h2n_scoped_target_normalization_vs_h2j_h2k_comparison_exists"]["passed"] is True
    assert checks["h2n_scoped_target_normalization_vs_h2j_h2l_comparison_exists"]["passed"] is True
    assert checks["h2n_scoped_target_normalization_vs_h2j_h2f_comparison_exists"]["passed"] is True
    assert checks["h2n_scoped_target_normalization_synthesis_exists"]["passed"] is True
    assert checks["h2n_scoped_target_normalization_report_figure_exists"]["passed"] is True
    assert checks["h2o_value_bearing_target_synthesis_h2m_live_exists"]["passed"] is True
    assert checks["h2o_value_bearing_target_synthesis_h2k_live_exists"]["passed"] is True
    assert checks["h2o_value_bearing_target_synthesis_h2l_live_exists"]["passed"] is True
    assert checks["h2o_value_bearing_target_synthesis_h2f_live_exists"]["passed"] is True
    assert checks["h2o_value_bearing_target_synthesis_vs_h2n_h2m_comparison_exists"]["passed"] is True
    assert checks["h2o_value_bearing_target_synthesis_vs_h2j_h2m_comparison_exists"]["passed"] is True
    assert checks["h2o_value_bearing_target_synthesis_vs_h2e_h2m_comparison_exists"]["passed"] is True
    assert checks["h2o_value_bearing_target_synthesis_vs_h2j_h2k_comparison_exists"]["passed"] is True
    assert checks["h2o_value_bearing_target_synthesis_vs_h2j_h2l_comparison_exists"]["passed"] is True
    assert checks["h2o_value_bearing_target_synthesis_vs_h2j_h2f_comparison_exists"]["passed"] is True
    assert checks["h2o_value_bearing_target_synthesis_report_exists"]["passed"] is True
    assert checks["h2o_value_bearing_target_synthesis_report_figure_exists"]["passed"] is True
    assert checks["h2p_contextual_surface_alias_routing_h2m_live_exists"]["passed"] is True
    assert checks["h2p_contextual_surface_alias_routing_h2k_live_exists"]["passed"] is True
    assert checks["h2p_contextual_surface_alias_routing_h2l_live_exists"]["passed"] is True
    assert checks["h2p_contextual_surface_alias_routing_h2f_live_exists"]["passed"] is True
    assert checks["h2p_contextual_surface_alias_routing_vs_h2o_h2m_comparison_exists"]["passed"] is True
    assert checks["h2p_contextual_surface_alias_routing_vs_h2n_h2m_comparison_exists"]["passed"] is True
    assert checks["h2p_contextual_surface_alias_routing_vs_h2j_h2m_comparison_exists"]["passed"] is True
    assert checks["h2p_contextual_surface_alias_routing_vs_h2e_h2m_comparison_exists"]["passed"] is True
    assert checks["h2p_contextual_surface_alias_routing_vs_h2o_h2k_comparison_exists"]["passed"] is True
    assert checks["h2p_contextual_surface_alias_routing_vs_h2o_h2l_comparison_exists"]["passed"] is True
    assert checks["h2p_contextual_surface_alias_routing_vs_h2o_h2f_comparison_exists"]["passed"] is True
    assert checks["h2p_contextual_surface_alias_routing_report_exists"]["passed"] is True
    assert checks["h2p_contextual_surface_alias_routing_report_figure_exists"]["passed"] is True
    assert checks["h2q_composed_surface_value_stale_packet_exists"]["passed"] is True
    assert checks["h2q_composed_surface_value_stale_h2p_live_exists"]["passed"] is True
    assert checks["h2q_composed_surface_value_stale_h2o_live_exists"]["passed"] is True
    assert checks["h2q_composed_surface_value_stale_h2n_live_exists"]["passed"] is True
    assert checks["h2q_composed_surface_value_stale_h2e_live_exists"]["passed"] is True
    assert checks["h2q_composed_surface_value_stale_vs_h2o_comparison_exists"]["passed"] is True
    assert checks["h2q_composed_surface_value_stale_vs_h2n_comparison_exists"]["passed"] is True
    assert checks["h2q_composed_surface_value_stale_vs_h2e_comparison_exists"]["passed"] is True
    assert checks["h2q_composed_surface_value_stale_report_exists"]["passed"] is True
    assert checks["h2q_composed_surface_value_stale_report_figure_exists"]["passed"] is True
    assert checks["h2r_composed_route_gating_h2q_live_exists"]["passed"] is True
    assert checks["h2r_composed_route_gating_vs_h2p_h2q_comparison_exists"]["passed"] is True
    assert checks["h2r_composed_route_gating_report_exists"]["passed"] is True
    assert checks["h2r_composed_route_gating_report_figure_exists"]["passed"] is True
    assert checks["h2r_transfer_backtest_report_exists"]["passed"] is True
    assert checks["h2r_transfer_backtest_report_figure_exists"]["passed"] is True
    assert checks["h2r_transfer_h2b_regression_gate_exists"]["passed"] is True
    assert checks["h2r_transfer_h1x_regression_gate_exists"]["passed"] is True
    assert checks["h2s_fresh_composed_holdout_packet_exists"]["passed"] is True
    assert checks["h2s_fresh_composed_holdout_h2r_live_exists"]["passed"] is True
    assert checks["h2s_fresh_composed_holdout_h2p_live_exists"]["passed"] is True
    assert checks["h2s_fresh_composed_holdout_h2o_live_exists"]["passed"] is True
    assert checks["h2s_fresh_composed_holdout_h2j_live_exists"]["passed"] is True
    assert checks["h2s_fresh_composed_holdout_h2r_vs_h2p_comparison_exists"]["passed"] is True
    assert checks["h2s_fresh_composed_holdout_h2r_vs_h2o_comparison_exists"]["passed"] is True
    assert checks["h2s_fresh_composed_holdout_h2r_vs_h2j_comparison_exists"]["passed"] is True
    assert checks["h2s_fresh_composed_holdout_synthesis_exists"]["passed"] is True
    assert checks["h2s_fresh_composed_holdout_report_figure_exists"]["passed"] is True
    assert checks["h2t_overreach_independence_packet_exists"]["passed"] is True
    assert checks["h2t_overreach_independence_h2r_live_exists"]["passed"] is True
    assert checks["h2t_overreach_independence_h2e_live_exists"]["passed"] is True
    assert checks["h2t_overreach_independence_h2j_live_exists"]["passed"] is True
    assert checks["h2t_overreach_independence_h2o_live_exists"]["passed"] is True
    assert checks["h2t_overreach_independence_h2p_live_exists"]["passed"] is True
    assert checks["h2t_overreach_independence_h2r_vs_h2e_comparison_exists"]["passed"] is True
    assert checks["h2t_overreach_independence_h2r_vs_h2j_comparison_exists"]["passed"] is True
    assert checks["h2t_overreach_independence_h2r_vs_h2o_comparison_exists"]["passed"] is True
    assert checks["h2t_overreach_independence_h2r_vs_h2p_comparison_exists"]["passed"] is True
    assert checks["h2t_overreach_independence_synthesis_exists"]["passed"] is True
    assert checks["h2t_overreach_independence_report_figure_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h2t_live_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h2t_vs_h2r_comparison_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h2s_transfer_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h2q_transfer_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h2m_transfer_exists"]["passed"] is True
    assert checks["h2u_negation_guard_transfer_comparisons_exist"]["passed"] is True
    assert checks["h2u_negation_guard_h2q_comparison_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h2m_comparison_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h2k_transfer_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h2k_comparison_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h2l_transfer_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h2l_comparison_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h2f_transfer_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h2f_comparison_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h2b_transfer_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h2b_comparison_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h1x_transfer_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h1x_comparison_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h1y_transfer_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h1y_comparison_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h1o_transfer_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h1o_comparison_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h1p_transfer_exists"]["passed"] is True
    assert checks["h2u_negation_guard_h1p_comparison_exists"]["passed"] is True
    assert checks["h2u_negation_guard_synthesis_exists"]["passed"] is True
    assert checks["h2u_negation_guard_report_figure_exists"]["passed"] is True
    assert checks["h2v_semantic_negation_packet_exists"]["passed"] is True
    assert checks["h2v_semantic_negation_h2j_live_exists"]["passed"] is True
    assert checks["h2v_semantic_negation_h2r_live_exists"]["passed"] is True
    assert checks["h2v_semantic_negation_h2u_live_exists"]["passed"] is True
    assert checks["h2v_semantic_negation_h2u_vs_h2r_comparison_exists"]["passed"] is True
    assert checks["h2v_semantic_negation_h2u_vs_h2j_comparison_exists"]["passed"] is True
    assert checks["h2v_semantic_negation_h2r_vs_h2j_comparison_exists"]["passed"] is True
    assert checks["h2v_semantic_negation_synthesis_exists"]["passed"] is True
    assert checks["h2v_semantic_negation_report_figure_exists"]["passed"] is True
    assert checks["h2w_semantic_target_preservation_h2v_live_exists"]["passed"] is True
    assert checks["h2w_semantic_target_preservation_vs_h2u_comparison_exists"]["passed"] is True
    assert checks["h2w_semantic_target_preservation_vs_h2r_comparison_exists"]["passed"] is True
    assert checks["h2w_semantic_target_preservation_vs_h2j_comparison_exists"]["passed"] is True
    assert checks["h2w_semantic_target_preservation_synthesis_exists"]["passed"] is True
    assert checks["h2w_semantic_target_preservation_report_figure_exists"]["passed"] is True
    assert checks["h2w_transfer_backtest_synthesis_exists"]["passed"] is True
    assert checks["h2w_transfer_backtest_report_figure_exists"]["passed"] is True
    assert checks["h2w_transfer_h2t_live_exists"]["passed"] is True
    assert checks["h2w_transfer_h1p_live_exists"]["passed"] is True
    assert checks["h2w_transfer_h2t_vs_h2u_comparison_exists"]["passed"] is True
    assert checks["h2w_transfer_h2t_vs_h2r_comparison_exists"]["passed"] is True
    assert checks["h2w_transfer_h1p_vs_h2u_comparison_exists"]["passed"] is True
    assert checks["h2x_cli_semantic_pressure_synthesis_exists"]["passed"] is True
    assert checks["h2x_cli_semantic_pressure_report_figure_exists"]["passed"] is True
    assert checks["h2x_cli_semantic_pressure_packet_exists"]["passed"] is True
    assert checks["h2x_cli_semantic_pressure_h2u_live_exists"]["passed"] is True
    assert checks["h2x_cli_semantic_pressure_h2w_live_exists"]["passed"] is True
    assert checks["h2x_cli_semantic_pressure_h2u_no_fallback_live_exists"]["passed"] is True
    assert checks["h2x_cli_semantic_pressure_h2w_no_fallback_live_exists"]["passed"] is True
    assert checks["h2x_cli_semantic_pressure_h2w_vs_h2u_comparison_exists"]["passed"] is True
    assert checks["h2x_cli_semantic_pressure_h2u_no_fallback_comparison_exists"]["passed"] is True
    assert checks["h2x_cli_semantic_pressure_h2w_no_fallback_comparison_exists"]["passed"] is True
    assert checks["h2y_scaled_cli_semantic_pressure_synthesis_exists"]["passed"] is True
    assert checks["h2y_scaled_cli_semantic_pressure_report_figure_exists"]["passed"] is True
    assert checks["h2y_scaled_cli_semantic_pressure_packet_exists"]["passed"] is True
    assert checks["h2y_scaled_cli_semantic_pressure_h2u_live_exists"]["passed"] is True
    assert checks["h2y_scaled_cli_semantic_pressure_h2w_live_exists"]["passed"] is True
    assert checks["h2y_scaled_cli_semantic_pressure_h2u_no_fallback_live_exists"]["passed"] is True
    assert checks["h2y_scaled_cli_semantic_pressure_h2w_no_fallback_live_exists"]["passed"] is True
    assert checks["h2y_scaled_cli_semantic_pressure_h2w_vs_h2u_comparison_exists"]["passed"] is True
    assert checks["h2y_scaled_cli_semantic_pressure_h2u_no_fallback_comparison_exists"]["passed"] is True
    assert checks["h2y_scaled_cli_semantic_pressure_h2w_no_fallback_comparison_exists"]["passed"] is True
    assert checks["h2z_boundary_ablation_synthesis_exists"]["passed"] is True
    assert checks["h2z_boundary_ablation_report_figure_exists"]["passed"] is True
    assert checks["h2z_stale_selection_negation_live_exists"]["passed"] is True
    assert checks["h2z_negated_component_live_exists"]["passed"] is True
    assert checks["h2z_combined_live_exists"]["passed"] is True
    assert checks["h2z_stale_vs_h2w_comparison_exists"]["passed"] is True
    assert checks["h2z_component_vs_h2w_comparison_exists"]["passed"] is True
    assert checks["h2z_combined_vs_h2w_comparison_exists"]["passed"] is True
    assert checks["h2z_combined_vs_stale_comparison_exists"]["passed"] is True
    assert checks["h2z_combined_vs_component_comparison_exists"]["passed"] is True
    assert checks["h3_cli_controller_holdout_synthesis_exists"]["passed"] is True
    assert checks["h3_cli_controller_holdout_report_figure_exists"]["passed"] is True
    assert checks["h3_cli_controller_holdout_packet_exists"]["passed"] is True
    assert checks["h3_cli_controller_holdout_h2w_live_exists"]["passed"] is True
    assert checks["h3_cli_controller_holdout_h2z_stale_live_exists"]["passed"] is True
    assert checks["h3_cli_controller_holdout_h2z_component_live_exists"]["passed"] is True
    assert checks["h3_cli_controller_holdout_h2z_combined_live_exists"]["passed"] is True
    assert checks["h3_cli_controller_holdout_h2z_stale_vs_h2w_comparison_exists"]["passed"] is True
    assert checks["h3_cli_controller_holdout_h2z_component_vs_h2w_comparison_exists"]["passed"] is True
    assert checks["h3_cli_controller_holdout_h2z_combined_vs_h2w_comparison_exists"]["passed"] is True
    assert checks["h3_cli_controller_holdout_h2z_combined_vs_stale_comparison_exists"]["passed"] is True
    assert checks["h3_cli_controller_holdout_h2z_combined_vs_component_comparison_exists"]["passed"] is True
    assert checks["h3a_controller_repair_synthesis_exists"]["passed"] is True
    assert checks["h3a_controller_repair_report_figure_exists"]["passed"] is True
    assert checks["h3a_controller_repair_stale_live_exists"]["passed"] is True
    assert checks["h3a_controller_repair_negative_live_exists"]["passed"] is True
    assert checks["h3a_controller_repair_combined_live_exists"]["passed"] is True
    assert checks["h3a_controller_repair_stale_vs_h2z_comparison_exists"]["passed"] is True
    assert checks["h3a_controller_repair_negative_vs_h2z_comparison_exists"]["passed"] is True
    assert checks["h3a_controller_repair_combined_vs_h2z_comparison_exists"]["passed"] is True
    assert checks["h3a_controller_repair_combined_vs_stale_comparison_exists"]["passed"] is True
    assert checks["h3a_controller_repair_combined_vs_negative_comparison_exists"]["passed"] is True
    assert checks["h3a_h2y_transfer_gate_synthesis_exists"]["passed"] is True
    assert checks["h3a_h2y_transfer_gate_figure_exists"]["passed"] is True
    assert checks["h3a_h2y_transfer_gate_live_exists"]["passed"] is True
    assert checks["h3a_h2y_transfer_gate_vs_h2z_comparison_exists"]["passed"] is True
    assert checks["h3a_h2y_transfer_gate_vs_h2w_comparison_exists"]["passed"] is True
    assert checks["h3a_transfer_backtest_synthesis_exists"]["passed"] is True
    assert checks["h3a_transfer_backtest_figure_exists"]["passed"] is True
    assert checks["h3a_transfer_h2t_live_exists"]["passed"] is True
    assert checks["h3a_transfer_h1p_live_exists"]["passed"] is True
    assert checks["h3a_transfer_h2t_vs_h2w_comparison_exists"]["passed"] is True
    assert checks["h3a_transfer_h1p_vs_h2w_comparison_exists"]["passed"] is True
    assert checks["h3b_h4_saturation_breaker_design_exists"]["passed"] is True
    assert checks["h3b_h4_saturation_breaker_figure_exists"]["passed"] is True
    assert checks["h3b_h4_saturation_breaker_score_contract_exists"]["passed"] is True
    assert checks["h3b_saturation_breaker_synthesis_exists"]["passed"] is True
    assert checks["h3b_saturation_breaker_figure_exists"]["passed"] is True
    assert checks["h3b_saturation_breaker_h3a_live_exists"]["passed"] is True
    assert checks["h3b_saturation_breaker_h2z_live_exists"]["passed"] is True
    assert checks["h3b_saturation_breaker_h2w_live_exists"]["passed"] is True
    assert checks["h3b_saturation_breaker_h2z_vs_h2w_comparison_exists"]["passed"] is True
    assert checks["h3b_saturation_breaker_h3a_vs_h2z_comparison_exists"]["passed"] is True
    assert checks["h3b_saturation_breaker_h3a_vs_h2w_comparison_exists"]["passed"] is True
    assert checks["h2x_packaged_semantic_pressure_workflow_config_exists"]["passed"] is True
    assert checks["script_analyze_visual_hard_slice_exactness.py_exists"]["passed"] is True
    assert checks["script_analyze_packaged_replay_gap.py_exists"]["passed"] is True
    assert checks["script_analyze_h1n_alias_transfer_contract_split.py_exists"]["passed"] is True
    assert checks["script_analyze_h1n_oracle_helper_ablation.py_exists"]["passed"] is True
    assert checks["script_analyze_h1n_oblique_misses.py_exists"]["passed"] is True
    assert checks["script_analyze_h1n_oblique_code_hints_delta.py_exists"]["passed"] is True
    assert checks["script_build_h1n_code_hints_transfer_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h1n_code_guard_transfer_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h1n_no_call_rescue_transfer_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h1o_control_factorial_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h1q_component_label_guard_transfer_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h1s_component_residual_transfer_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2a_stale_selection_transfer_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2b_residual_exactness_packet.py_exists"]["passed"] is True
    assert checks["script_build_h2b_residual_exactness_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2c_scoped_residual_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h1n_oracle_transfer_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2k_target_decoy_overlap_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2l_target_normalization_overreach_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2m_less_direct_overreach_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2n_scoped_target_normalization_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2o_value_bearing_target_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2p_contextual_surface_alias_routing_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2q_composed_surface_value_stale_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2r_composed_route_gating_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2s_fresh_composed_holdout_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2t_overreach_independence_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2u_negation_guard_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2v_semantic_negation_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2w_semantic_target_preservation_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2w_transfer_backtest_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2x_cli_semantic_pressure_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2y_scaled_cli_semantic_pressure_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h2z_boundary_ablation_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h3_cli_controller_holdout_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h3a_controller_repair_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h3a_h2y_transfer_gate_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h3a_transfer_backtest_synthesis.py_exists"]["passed"] is True
    assert checks["script_build_h3b_h4_saturation_breaker_design.py_exists"]["passed"] is True
    assert checks["script_build_h3b_saturation_breaker_synthesis.py_exists"]["passed"] is True
    assert checks["script_run_visual_hard_slice_probe_packet.py_exists"]["passed"] is True
    assert checks["script_build_visual_hard_slice_replay_packet.py_exists"]["passed"] is True
    assert checks["v3_skipped_live_decision_exists"]["passed"] is True
    assert checks["paper_outline_exists"]["severity"] == "recommended"

    assert (tmp_path / "publication_readiness_audit.md").exists()
    assert (tmp_path / "publication_readiness_audit.json").exists()
    assert (tmp_path / "manifest.json").exists()
    assert (tmp_path / "tables" / "publication_readiness_checks.csv").exists()
